EmployeesProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls'))
]

employees/urls.py
from django.urls import path

from employees.views import AddProgLangView, AddDepartmentView
from employees.views import ListEmployees, AddEmployee, EditEmployee, DeleteEmployee

urlpatterns = [
    path('', ListEmployees.as_view(), name='index'),
    path('add/', AddEmployee.as_view(), name='add_employee'),
    path('<int:pk>/edit/', EditEmployee.as_view(), name='edit_employee'),
    path('<int:pk>/delete/', DeleteEmployee.as_view(), name='delete_employee'),
    path('proglang/add/', AddProgLangView.as_view(), name='add_proglang'),
    path('department/add/', AddDepartmentView.as_view(), name='add_department')
]

employees/models.py
from django.db import models


# Create your models here.


class ProgrammingLanguageModel(models.Model):
    title = models.CharField(max_length=150, blank=False, unique=True)

    def __str__(self):
        return self.title


class DepartmentModel(models.Model):
    title = models.CharField(max_length=150, blank=False, unique=True)
    floor = models.IntegerField(blank=False)

    def __str__(self):
        return self.title


class EmployeeModel(models.Model):
    class Sex(models.TextChoices):
        Male = "МУЖ", "Мужской",
        Female = "Жен.", "Женский"

    first_name = models.CharField(max_length=255, null=False, blank=False)
    last_name = models.CharField(max_length=255, null=False, blank=False)
    age = models.IntegerField(blank=False, null=False)
    sex = models.CharField(max_length=10, blank=False, choices=Sex.choices, verbose_name='Пол')
    department = models.ForeignKey('DepartmentModel', on_delete=models.CASCADE, blank=True, null=True)
    programming_language = models.ForeignKey('ProgrammingLanguageModel', on_delete=models.PROTECT)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['first_name', 'last_name'], name='first_last_name')
        ]

    def __str__(self):
        return self.first_name + ' ' + self.last_name

employees/forms.py
from django import forms
from django.core import validators

from employees.models import EmployeeModel, DepartmentModel, ProgrammingLanguageModel


class AddEmployeeForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', required=True, widget=forms.TextInput(
        attrs={id: 'fname'}
    ))
    last_name = forms.CharField(label='Фамилия', required=True)
    age = forms.IntegerField(label='Возраст', required=True, validators=[
        validators.MinValueValidator(limit_value=16)
    ])
    department = forms.ModelChoiceField(label='Отдел', queryset=DepartmentModel.objects.all(),
                                        empty_label='Выберите отдел')
    sex = forms.ChoiceField(label='Пол', choices=EmployeeModel.Sex.choices)
    programming_language = forms.ModelChoiceField(label='Язык программирования',
                                                  queryset=ProgrammingLanguageModel.objects.all(),
                                                  empty_label='Выберите язык')

    class Meta:
        model = EmployeeModel
        fields = '__all__'


class EditEmployeeForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', required=True)
    last_name = forms.CharField(label='Фамилия', required=True)
    age = forms.IntegerField(label='Возраст', required=True, validators=[
        validators.MinValueValidator(limit_value=16)
    ])
    department = forms.ModelChoiceField(label='Отдел', queryset=DepartmentModel.objects.all())
    programming_language = forms.ModelChoiceField(label='Язык программирования',
                                                  queryset=ProgrammingLanguageModel.objects.all())

    class Meta:
        model = EmployeeModel
        fields = ('first_name', 'last_name', 'age', 'department', 'programming_language',)


'''Добавляем язык программирования в справочник'''


class AddPLForm(forms.ModelForm):
    title = forms.CharField(max_length=150, min_length=1, label='Язык программирования')

    class Meta:
        model = ProgrammingLanguageModel
        fields = '__all__'


'''Добавляем отдел в справочник'''


class AddDepartmentForm(forms.ModelForm):
    title = forms.CharField(max_length=150, min_length=1, label='Отдел')
    floor = forms.IntegerField(min_value=0, label='Этаж')

    class Meta:
        model = DepartmentModel
        fields = '__all__'

employees/views.py
import json

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from employees.forms import AddEmployeeForm, EditEmployeeForm, AddPLForm, AddDepartmentForm
from employees.models import EmployeeModel, ProgrammingLanguageModel, DepartmentModel


# Create your views here.


class ListEmployees(ListView):
    template_name = 'employees/index.html'
    model = EmployeeModel
    context_object_name = 'employee_list'


class DeleteEmployee(DeleteView):
    model = EmployeeModel
    template_name = 'employees/delete_employee.html'
    success_url = reverse_lazy('index')
    context_object_name = 'employee'


class AddEmployee(CreateView):
    template_name = 'employees/add_employee.html'
    form_class = AddEmployeeForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(AddEmployee, self).get_context_data(**kwargs)
        results = []
        for item in EmployeeModel.objects.all():
            results.append(item.first_name)
        context['names'] = json.dumps(results)
        return context


class EditEmployee(UpdateView):
    template_name = 'employees/edit_employee.html'
    form_class = EditEmployeeForm
    success_url = '/'
    model = EmployeeModel


class AddProgLangView(CreateView):
    template_name = 'employees/admin/add_programming_language.html'
    form_class = AddPLForm
    model = ProgrammingLanguageModel
    success_url = '/'


class AddDepartmentView(CreateView):
    template_name = 'employees/admin/add_department.html'
    form_class = AddDepartmentForm
    model = DepartmentModel
    success_url = '/'

templates/employees/add_employee.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавление сотрудника</title>
    <link href="{% static 'employees/form_add.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
</head>
<body>
<h4 class="h4">Добавление сотрудника</h4>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <script>
        $(() => {
            $("#id_first_name").autocomplete({
                source: JSON.parse("{{ names | escapejs }}"),
                minLength: 1
            })
        })
    </script>
    <button type="submit">Добавить</button>
    <a href="{% url 'index' %}">Отмена</a>
</form>
</body>
</html>

templates/employees/admin/add_department.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавить отдел</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
    <a href="{% url 'index' %}">Отмена</a>
</form>
</body>
</html>

templates/employees/admin/add_programming_language.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавление языка программирования</title>
</head>
<body>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
    <a href="{% url 'index' %}">Отмена</a>
</form>
</body>
</html>

templates/employees/delete_employee.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Удалить запись</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить запись о сотруднике {{ employee.first_name }}</p>
    <button type="submit">Подтвердить</button>
</form>
</body>
</html>

templates/employees/edit_employee.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Редактировать сведения о сотруднике</title>
</head>
<body>
<form id="edit-form" method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Внести изменения</button>
</form>
</body>
</html>

templates/employees/index.html
<html lang="ru">
<head>
    <meta charset="UTF-8" lang="ru">
    <title>Список сотрудников</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
</head>
<body>
<div id="add-employee">
    <a href="{% url 'add_employee' %}" class="link-primary link-dark">Добавить сведения о сотруднике</a>
</div>
<div id="add-department">
    <a href="{% url 'add_department' %}" class="link-primary link-dark">Добавить отдел</a>
</div>
<div id="add-proglang">
    <a href="{% url 'add_proglang' %}" class="link-primary link-dark">Добавить язык программирования</a>
</div>
{% if employee_list is not None %}
    <table class="table">
        <thead>
        <th scope="col" class="table-light">Имя</th>
        <th scope="col" class="table-light">Фамилия</th>
        <th scope="col" class="table-light">Пол</th>
        <th scope="col" class="table-light">Возраст</th>
        <th scope="col" class="table-light">Отдел</th>
        <th scope="col" class="table-light">Язык программирования</th>
        <th scope="col" class="table-light"></th>
        </thead>
        <tbody>
        {% for employee in employee_list %}
            <tr>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name }}</td>
                <td>{{ employee.sex }}</td>
                <td>{{ employee.age }}</td>
                <td>{{ employee.department.title }}</td>
                <td>{{ employee.programming_language }}</td>
                <td>
                    <a href="{% url 'edit_employee' pk=employee.pk %}">Изменить</a>
                    <a href="{% url 'delete_employee' pk=employee.pk %}">Удалить</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
</body>
</html>